---
title: "BC Chronic Disease Capstone Report"
subtitle: "Capstone Partner: BC Office of the Provincial Health Officer, Mentor: Daniel Chen"
author: "Team: Jennifer Hoang, Jessie Wong, Mahmoodur Rahman, Irene Yan"
date: "`r Sys.Date()`"
output: 
  bookdown::pdf_document2
header-includes:
 \usepackage{float}
bibliography: capstone-report.bib
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H')
```
\newpage

# Executive Summary 

The BC Chronic Disease Registry (BCCDR) is a data product that captures
information about the rates of new and persistent cases of 25 different chronic
diseases across the Province of British Columbia. Crude and age-standardized
rates of disease are recorded for different health boundary types, including HAs 
(Health Authorities) and CHSAs (Community Health Service Areas), as well as for demographic
variables such as sex. In this project we aim to develop and analysis pipeline to describe
the temporal trends in the data, and the build an interactive dashboard that will allow users
of all technical expertise to explore and visualize spatial and temporal information of the 
disease rates. This proposal will outline the approach we took to
tackle this problem and a description of our final data product.

\newpage

# Introduction 

Millions of people in BC live with a chronic disease, so it's important
to understand and interpret the distribution of diseases
throughout the province for a variety of reasons. We may want to know
how to best allocate healthcare resources, or to identify if a specific
region is experiencing rapid growth of a disease. The dashboard is a
tool that will allow healthcare professionals and eventually the general
public to access the disease information and answer these questions.

The BC CDR captures 3 different types of rates that we will be incorporating into
our dashboard. Incidence Rate is the rate at which new cases occur in
a specified population during a specified time period; Lifetime
Prevalence is the proportion of individuals who have had the condition
for at least part of their lives, and Active Healthcare Contact
Prevalence are the cases for which a patient seeks healthcare services
for relapsing - remitting conditions. Each of these 3 rates are available
as Crude or Age Standardized rates. Age Standardized rates are adjusted
to the standard population, and are calculated as if all regions shared the same age structure,
that of the 2011 Canadian Census. Crude rates are not adjusted to the standard population, 
and represent the number of cases in a specific geographic region divided by the population
at risk in that region. For each disease rate metric, the data is stratified by year, 
sex and by region at various tiers. In this project we
focus on the least and the most granular spatial health boundaries, which are
the 5 Health Authorities (HA) and the 195 Community Health
Service Areas (CHSA).

## Temporal Modeling





## Dashboard

The dashboard facilitates the exploration and visualization of spatial and temporal trends of 
25 different chronic diseases across the Province of British Columbia. The dashboard consists of 4 main tabs,
which are Information, By Disease, By Region, and Data. The Information tab contains a description of the dashboard
usage, and definitions of rate types, diseases, and data variables. The By Disease tab allows for 
the comparisons of one disease over several HAs or CHSAs, while the By Region tab allows for the 
comparisons of several diseases in one particular HA or CHSA. The Data tab retrieves and displays all data specified
by the user, and contains a button to download the data if the user wishes to do so.



# Data Science Techniques

Several different data science tools and techniques were used
throughout the project to accomplish the project deliverable. Some tools
were familiar to the team, while others tools were newly learned. The
tools and techniques used in each aspect of the project are described in
this section.

## Temporal Modeling

For temporal modeling, we selected the INLA approximation approach for Bayesian modeling. 
INLA is faster compared to Markov Chain Monte Carlo simulation based methods (@wang_2018), 
and since there were over 10,000 combinations of 
CHSAs, diseases, and rates to be modeled, computational speed was a key consideration.
Potential disadvantages of INLA include that small variations between repeated runs 
can occur as a trade-off for the faster computation gained by using multiple cores (@wang_2018). 
However, these small variations are well beyond the significant digits of our data, therefore, we considered this to be an acceptable trade-off.

With INLA, we used a Gamma generalized linear model to smoothen the 
age-standardized rate, which is a continuous, positive response. The effect of
year was modeled using a Random Walk prior to account for temporal autocorrelation.
On each CHSA, disease, and rate, a first order random walk (RW1) 
and second order random walk (RW2) model was fit and the best RW model was selected using the
Widely Applicable Information Criterion (WAIC).

A limitation of this approach was that rare diseases with low incidence and prevalence rates
could not be modeled, because the Gamma distribution does not provide support for values of 0.
Despite this limitation, our model was applied to 84% of incidence rate data, 91% of HSC prevalence rate data, and 98% of life prevalence rate data.

Alternative approaches that were explored to accommodate the zero values were to
use the Tweedie distribution, which can accommodate positive continuous data
with a point mass at zero (@kurz_2017). 
The implementation of the Tweedie distribution in R-INLA remains experimental and subject to change, 
however, and this approach was not further pursued due to poor model fit on our data. 
Zero-inflated gamma and hurdle gamma models were also investigated to accommodate zero values,
but were not supported by R-INLA at the time of this project.

## Dashboard

While the majority of the dashboard was built using R, several other languages were also needed in order to customize and run the
dashboard, including JavaScript, HTML, and CSS. R was used to build the Shiny App framework, as well as for all of the data wrangling,
processing, and plotting. Javascript was needed to create customized functions that were otherwise impossible in R, such as for the 
map animation in the By Disease tab. Some Javascript components were also needed to optimize the processing speed of the app. 
HTML was used for text formatting and other styling options throughout the dashboard, including on the Information pages, in the plot hover 
labels, and the plot legends. CSS was needed for reusable customized styling, and streamlined the style modification process in the dashboard. 
Much of the element layouts, colours, and spacing were achieved through the use of CSS.

Over 15 different packages were used to create the dashboard, with the most important ones being Shiny, Leaflet, and Plotly. Shiny was used 
to build the overall app framework, and was a requirement on part of the Capstone Project. Leaflet was used to create the interactive map on the
By Disease tab, and was chosen due to its easy integration with Shiny and Plotly. However, the difficulty with using Leaflet is that it does 
not easily animate within R and Shiny, and thus the custom Javascript functions were needed in this case. Plotly was used to create the interactive plots 
in both the By Disease and By Region tab. This plotting library was preferred over other options such as ggplot because of its built-in interactive
components, and its ability to create smooth animations.


# Data Product and Results



## Temporal Modeling

## Dashboard




# Conclusion and Recommendations


# References
